FROM rackattack-nas.dc1:5000/ubuntu-python-base:1000.7.0-g21c1e3c
COPY apt-packages-dev.in /tmp/
RUN apt-get update -y && \
  apt-get upgrade -y && \
  apt-get install -y $(cat /tmp/apt-packages-dev.in) && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
COPY pip.conf /etc/pip.conf
COPY dev-requirements.in /tmp/
RUN python -m pip install -r /tmp/dev-requirements.in --no-cache-dir --break-system-packages
COPY requirements.txt /tmp/
RUN python -m pip install -r /tmp/requirements.txt --no-cache-dir --break-system-packages
