
[global]
trusted-host = strato-pypi.dc1.strato

[install]
index-url = http://strato-pypi.dc1.strato:5002/root/pypi
extra-index-url = http://strato-pypi.dc1.strato:5002/strato/staging http://strato-pypi.dc1.strato:5002/strato/dev
